version: '3.4'

services:
  db:
    image:  mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: 'mssql_db'
    volumes:
    - ./data :/var/opt/mssql/backup
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
        